# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/cherry/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/cherry/proprietary/vendor/etc/nfc/hardfault.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/hardfault.cfg \
    vendor/huawei/cherry/proprietary/vendor/etc/permissions/com.android.nfc.helper.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.android.nfc.helper.xml \
    vendor/huawei/cherry/proprietary/vendor/etc/permissions/com.android.qualcomm.qti.nfc_extras.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.android.qualcomm.qti.nfc_extras.xml \
    vendor/huawei/cherry/proprietary/vendor/etc/permissions/com.gsma.services.nfc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.gsma.services.nfc.xml \
    vendor/huawei/cherry/proprietary/vendor/etc/permissions/com.gsma.services.utils.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.gsma.services.utils.xml \
    vendor/huawei/cherry/proprietary/vendor/etc/permissions/com.vzw.nfc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.vzw.nfc.xml \
    vendor/huawei/cherry/proprietary/vendor/firmware/Signedrompatch_v20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Signedrompatch_v20.bin \
    vendor/huawei/cherry/proprietary/vendor/firmware/Signedrompatch_v21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Signedrompatch_v21.bin \
    vendor/huawei/cherry/proprietary/vendor/firmware/Signedrompatch_v24.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Signedrompatch_v24.bin \
    vendor/huawei/cherry/proprietary/vendor/firmware/Signedrompatch_v30.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Signedrompatch_v30.bin \
    vendor/huawei/cherry/proprietary/vendor/firmware/fused_nvm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fused_nvm.bin \
    vendor/huawei/cherry/proprietary/vendor/firmware/nfc_test.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc_test.bin \
    vendor/huawei/cherry/proprietary/vendor/framework/com.android.nfc.helper.jar:$(TARGET_COPY_OUT_VENDOR)/framework/com.android.nfc.helper.jar \
    vendor/huawei/cherry/proprietary/vendor/framework/com.android.qualcomm.qti.nfc_extras.jar:$(TARGET_COPY_OUT_VENDOR)/framework/com.android.qualcomm.qti.nfc_extras.jar \
    vendor/huawei/cherry/proprietary/vendor/framework/com.gsma.services.nfc.jar:$(TARGET_COPY_OUT_VENDOR)/framework/com.gsma.services.nfc.jar \
    vendor/huawei/cherry/proprietary/vendor/framework/com.gsma.services.utils.jar:$(TARGET_COPY_OUT_VENDOR)/framework/com.gsma.services.utils.jar \
    vendor/huawei/cherry/proprietary/vendor/framework/com.vzw.nfc.jar:$(TARGET_COPY_OUT_VENDOR)/framework/com.vzw.nfc.jar \
    vendor/huawei/cherry/proprietary/vendor/lib/hw/nfc_nci.qc199x.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/nfc_nci.qc199x.default.so \
    vendor/huawei/cherry/proprietary/vendor/lib/libqnfc-nci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqnfc-nci.so \
    vendor/huawei/cherry/proprietary/vendor/lib/libqnfc_nci_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqnfc_nci_jni.so
